<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260715114259 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, album_title VARCHAR(255) NOT NULL, album_cover VARCHAR(255) DEFAULT NULL, info VARCHAR(255) DEFAULT NULL, release_date DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lyrics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, line VARCHAR(255) NOT NULL, time INT DEFAULT NULL, song_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BDA6C66A0BDB2F3 ON lyrics (song_id)');
        $this->addSql('CREATE TABLE song (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, song_title VARCHAR(255) NOT NULL, audio_file VARCHAR(255) NOT NULL, length INT NOT NULL, info VARCHAR(255) DEFAULT NULL, album_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33EDEEA11137ABCF ON song (album_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE lyrics ADD CONSTRAINT FK_3BDA6C66A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE song ADD CONSTRAINT FK_33EDEEA11137ABCF FOREIGN KEY (album_id) REFERENCES album (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lyrics DROP CONSTRAINT FK_3BDA6C66A0BDB2F3');
        $this->addSql('ALTER TABLE song DROP CONSTRAINT FK_33EDEEA11137ABCF');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE lyrics');
        $this->addSql('DROP TABLE song');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
